export const theme = {
  colors: {
    background: '#F8FAFC',
    backgroundBoard: '#FFFFFF',
    mobileCoulmnBackground: '#F1F5F9',
    textPrimary: '#1E293B',
    textSecondary: '#FFFFFF',
    textTertiary: '#666',
    hoverBlue: '#007bff',
    taskBackground: '#fff',
    taskBoxShadow: '#1717170F',
    taskBorder: '#eee',
    taskTitle: '#333',
    taskDescription: '#666',
    priorityHigh: '#FFF1F2',
    priorityMediumBackground: '#eef2ff',
    priorityMediumText: '#4f46e5',
    priorityHighText: '#F43F5E',
    priorityLowText: '#22C55E',
    priorityLow: '#F0FDF4',
    priorityDefault: '#ffc107',
    taskDraggingBorder: '#ccc',
    editMenuBackground: '#fff',
    editMenuBorder: '#eee',
    editMenuItem: '#333',
    editMenuItemHover: '#f0f0f0',
    editMenuShadow: '#0000001a',
  },
  fontSizes: {
    small: '0.8rem',
    medium: '0.9rem',
    large: '1.2rem',
    xl: '24px',
    taskTitle: '1rem',
  },
  padding: {
    small: '3px 6px',
    medium: '16px',
    large: '20px',
    addTaskWrapper: '15px',
    columnTitleBar: '10px',
    addButton: '5px 10px',
    taskItem: '15px',
    editMenu: '10px 0',
    editMenuItem: '8px 20px',
  },
  borderRadius: {
    small: '4px',
    medium: '30px',
    large: '40px',
    addTask: '30px',
    addTaskWrapper: '30px',
    taskItem: '30px',
    priority: '30px',
    editMenu: '30px',
  },
  fontFamily: {
    primary: 'Plus Jakarta Sans, sans-serif',
  },
  breakpoints: {
    sm: '390px',
    md: '768px',
  },
  fontWeights: {
    semiBold: 600,
    medium: 500,
  },
  boxShadow: {
    taskItem: '0 2px 4px #1717170F',
    taskDragging: '2px 2px 5px  #0000001A',
    editMenu: '0 1px 2px #0000001A',
  },
  border: {
    taskDragging: '1px dashed',
    editMenu: '1px solid #eee',
  },
  zIndex: {
    editMenu: 10,
  },
};
